apiVersion: apps/v1
kind: Service
metadata:
  name: backend-service
spec:
 type: NodePort
selector:
  app: aicoolgen-backend
ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    newport: 30080
