apiVersion: v1
kind: Service
metadata:
  name: backend-node-service
spec:
  type: NodePort
  selector:
    app: aicoolgen-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: aicoolgen-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
