apiVersion: v1
kind: Service
metadata:
  name: frontend-node-service
spec:
  type: NodePort
  selector:
    app: aicoolgen-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: aicoolgen-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
